### PR TITLE
Fix possible fd leak with threaded runtime

### LINKED ISSUE #27: File descriptors leak
`tokio-compat` runtime leaks file descriptors on `drop`.

I prepared a repo with a minimal example to demonstrate the issue: https://github.com/timberio/tokio-fds-issue

### PR DESCRIPTION
**Pull request by LucioFranco**
This PR introduces a fix where creating many runtimes in a loop will
cause an fd leak. This is because storing a strong arc within each
`on_thread_start` fn will cause the runtime handle to not be deallocated
when the `compat::Runtime` is dropped. To avoid this we only store a
weak pointer within the `on_thread_start` fn and attempt to upgrade it
to get the handle. Since, `on_thread_start` is generally always called
while the tokio runtime is not dropped the upgrade should not fail. This
then allows us to drop the runtime and deallocate the handle by storing
the only long lived strong arc within `compat::Runtime`.

I've verified this fixes our repro and doesn't leak fds on our
benchmarks where we orignally discovered this issue.

Closes #27

Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

### CODE REVIEW

File: src/runtime/threadpool/builder.rs [hunk 1]
```diff
@@ -163,7 +163,21 @@ impl Builder {
         let compat_reactor = compat_bg.reactor().clone();
         let compat_sender: Arc<RwLock<Option<super::CompatSpawner<tokio_02::runtime::Handle>>>> =
             Arc::new(RwLock::new(None));
-        let compat_sender2 = compat_sender.clone();
+
+        // We need a weak ref here so that when we pass this into the
+        // `on_thread_start` closure its stored as a _weak_ ref and not
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: nit:
```suggestion
        // `on_thread_start` closure it's stored as a _weak_ ref and not
```

File: src/runtime/threadpool/builder.rs [hunk 2]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        // a strong one. This is important because tokio 0.2's runtime
+        // should shutdown when the compat Runtime has been dropped. There
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: nit:
```suggestion
        // should shut down when the compat Runtime has been dropped. There
```

File: src/runtime/threadpool/builder.rs [hunk 3]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        // can be a race condition where we hold onto an extra Arc which holds
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: nit:
```suggestion
        // can be a race condition where we hold onto an extra Arc, which holds
```

File: src/runtime/threadpool/builder.rs [hunk 4]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        // a runtime handle beyond the drop. This casuses the tokio runtime to
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]:
```suggestion
        // a runtime handle beyond the drop. This causes the tokio 0.2 runtime to
```

File: src/runtime/threadpool/builder.rs [hunk 5]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        // not shutdown and leak fds.
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: nit:
```suggestion
        // not shut down and leak fds.
```

File: src/runtime/threadpool/builder.rs [hunk 6]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        //
+        // Tokio's threaded_scheduler will spawn threads that each contain a arced
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: nit:
```suggestion
        // Tokio 0.2's threaded_scheduler will spawn threads that each contain an arced
```

File: src/runtime/threadpool/builder.rs [hunk 7]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        // ref to the `on_thread_start` fn. If the runtime shutsdown but there is still
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]:
```suggestion
        // ref to the `on_thread_start` fn. If the runtime shuts down but there is still
```

File: src/runtime/threadpool/builder.rs [hunk 8]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        // access to a runtime handle the mio driver will not shutdown. To avoid this we
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]:
```suggestion
        // access to a runtime handle, the mio driver will not shutdown. To avoid this we
```

File: src/runtime/threadpool/builder.rs [hunk 9]
```diff
@@ -163,7 +163,21 @@ impl Builder {
...
+        // only want the `on_thread_start` to hold a weak ref and attempt to check async if
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: what do you mean by "check async"?

File: src/runtime/threadpool/builder.rs [hunk 10]
```diff
@@ -172,12 +186,19 @@ impl Builder {
             .enable_all()
             .on_thread_start(move || {
                 // We need the threadpool's sender to set up the default tokio
-                // 0.1 executor.
-                let lock = compat_sender2.read().unwrap();
+                // 0.1 executor. We also need to upgrade the weak pointer, if the
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: nit:
```suggestion
                // 0.1 executor. We also need to upgrade the weak pointer. If the
```

File: src/runtime/threadpool/builder.rs [hunk 11]
```diff
@@ -172,12 +186,19 @@ impl Builder {
...
+                // pointer is no longer valid then the runtime has shutdown and the
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]:
```suggestion
                // pointer is no longer valid, then the runtime has shut down and the
```

File: src/runtime/threadpool/builder.rs [hunk 12]
```diff
@@ -172,12 +186,19 @@ impl Builder {
...
+                // handle is no longer available.
+                //
+                // This upgrade will only fail if the compat runtime has been dropped.
+                let sender = compat_sender2.upgrade().expect("Compat runtime shutdown.");
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: the upgrade failing is a bug, rather than a user error, correct? i'd prefer it if we could make it a little clearer in the panic message that this was an internal error. not a big deal as AFAICT this shouldn't ever actually happen?

File: src/runtime/threadpool/builder.rs [hunk 13]
```diff
@@ -172,12 +186,19 @@ impl Builder {
...
+                let lock = sender.read().unwrap();
                 let compat_sender = lock
                     .as_ref()
                     .expect("compat executor needs to be set before the pool is run!")
                     .clone();
+                drop(lock);
+                drop(sender);
```
Comment (hawkw) [inline src/runtime/threadpool/builder.rs]: these should be dropped after the call to `set_guards` anyway, as the function returns — is there a reason we need to drop them _before_ calling `set_guards`? if so, it would be nice to have a comment explaining that.

File: src/runtime/threadpool/mod.rs [hunk 14]
```diff
@@ -43,6 +48,10 @@ pub struct Runtime {
     /// Idleness tracking.
     idle: idle::Idle,
     idle_rx: idle::Rx,
+
+    // This should store the only long living strong ref to the handle
+    // and once Runtime is dropped it should also deallocate.
```
Comment (hawkw) [inline src/runtime/threadpool/mod.rs]: nit:
```suggestion
    // This should store the only long-living strong ref to the handle,
    // and once the Runtime is dropped, it should also be deallocated.
```

**Review by hawkw — APPROVED** [review]
the change looks good to me. I commented on a few minor nits, including some proof-reading of the comments added in this PR. besides that, the fix seems correct. thanks for figuring this out!

File: src/runtime/threadpool/builder.rs (hunk 9 above)
Comment (LucioFranco) [reply src/runtime/threadpool/builder.rs]: So this fn gets run at some point async in the future and we have no control over when it gets called. Because of this I want to point out that it may happen but you don't know when.

File: src/runtime/threadpool/builder.rs (hunk 12 above)
Comment (LucioFranco) [reply src/runtime/threadpool/builder.rs]: Yeah, agreed, let me fix this up.

File: src/runtime/threadpool/builder.rs (hunk 13 above)
Comment (LucioFranco) [reply src/runtime/threadpool/builder.rs]: Yeah, I mostly added them to be explicit, will remove them :+1:
